language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-18
    - android-28
    #- sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_script:
  # Create and start emulator
  #- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  #- emulator -avd test -no-skin -no-audio -no-window &
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &

script:
   #- ./gradlew compileReleaseSources
   - ./gradlew assemble
   - ls -l -R app/build/outputs/apk

#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file: "app/build/outputs/apk/release/app-release-unsigned.apk"
#  skip_cleanup: true
#  draft: true

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  file: "app/build/outputs/apk"
  bucket: "travis-ci-apk"
  skip_cleanup: true
  on:
    all_branches: true